# permissions for end users to edit wildflyservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wildflyserver-editor-role
rules:
- apiGroups:
  - wildfly.org
  resources:
  - wildflyservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wildfly.org
  resources:
  - wildflyservers/status
  verbs:
  - get
