name: Go

env:
  REGISTRY: quay.io
  REGISTRY_USER: "wildfly+github_actions"
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_ROBOT_PASSWORD }}

on:
  push:
    branches: [ main, 0.5.x ]
  pull_request:
    branches: [ main, 0.5.x ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.3
    - name: Build
      run: make build
    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.9.0
      with:
        minikube version: v1.31.2
        kubernetes version: v1.24.0
        driver: docker
    - name: Load WildFly images used for testing
      run: |-
        minikube image load --pull=true quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0
        minikube image load --pull=true quay.io/wildfly-quickstarts/wildfly-operator-quickstart:bootable-21.0
        minikube image load --pull=true quay.io/wildfly-quickstarts/clusterbench:latest
    - name: Containerized End-to-End Tests
      run: eval $(minikube -p minikube docker-env) && make test-e2e-minikube
    - name: Docker Login to Quay.io (main only)
      uses: docker/login-action@v3.0.0
      if: github.ref == 'refs/heads/main'
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
    - name: Build and Push Image (main only)
      if: github.ref == 'refs/heads/main'
      run: make manifests docker-build docker-push
    - name: Push documentation to gh-pages (main only)
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        source_dir: ./doc

