# This is a basic workflow to help you get started with Actions
name: Push Tag to Container Registry

env:
  REGISTRY: quay.io
  REGISTRY_USER: "wildfly+github_actions"
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_ROBOT_PASSWORD }}

# Controls when the action will run. 
on:
  release:
    types:
    - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.13
      - name: Docker Login to Quay.io (main only)
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Build and Push Image Tag
        run: IMG="quay.io/wildfly/wildfly-operator:${GITHUB_REF##*/}" make manifests docker-build docker-push
